//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISplit")]
public interface ISplit
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISplit/Text", ReplyAction="http://tempuri.org/ISplit/TextResponse")]
    string[] Text(string str);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISplit/Text", ReplyAction="http://tempuri.org/ISplit/TextResponse")]
    System.Threading.Tasks.Task<string[]> TextAsync(string str);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISplitChannel : ISplit, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SplitClient : System.ServiceModel.ClientBase<ISplit>, ISplit
{
    
    public SplitClient()
    {
    }
    
    public SplitClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SplitClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SplitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SplitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] Text(string str)
    {
        return base.Channel.Text(str);
    }
    
    public System.Threading.Tasks.Task<string[]> TextAsync(string str)
    {
        return base.Channel.TextAsync(str);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IInfo")]
public interface IInfo
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfo/PostInfo", ReplyAction="http://tempuri.org/IInfo/PostInfoResponse")]
    string PostInfo(long iin, string surname, string firstname, string patronymic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfo/PostInfo", ReplyAction="http://tempuri.org/IInfo/PostInfoResponse")]
    System.Threading.Tasks.Task<string> PostInfoAsync(long iin, string surname, string firstname, string patronymic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfo/GetInfo", ReplyAction="http://tempuri.org/IInfo/GetInfoResponse")]
    Models.Profiles[] GetInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfo/GetInfo", ReplyAction="http://tempuri.org/IInfo/GetInfoResponse")]
    System.Threading.Tasks.Task<Models.Profiles[]> GetInfoAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IInfoChannel : IInfo, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InfoClient : System.ServiceModel.ClientBase<IInfo>, IInfo
{
    
    public InfoClient()
    {
    }
    
    public InfoClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InfoClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string PostInfo(long iin, string surname, string firstname, string patronymic)
    {
        return base.Channel.PostInfo(iin, surname, firstname, patronymic);
    }
    
    public System.Threading.Tasks.Task<string> PostInfoAsync(long iin, string surname, string firstname, string patronymic)
    {
        return base.Channel.PostInfoAsync(iin, surname, firstname, patronymic);
    }
    
    public Models.Profiles[] GetInfo()
    {
        return base.Channel.GetInfo();
    }
    
    public System.Threading.Tasks.Task<Models.Profiles[]> GetInfoAsync()
    {
        return base.Channel.GetInfoAsync();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAuth")]
public interface IAuth
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Register", ReplyAction="http://tempuri.org/IAuth/RegisterResponse")]
    string Register(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Register", ReplyAction="http://tempuri.org/IAuth/RegisterResponse")]
    System.Threading.Tasks.Task<string> RegisterAsync(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Login", ReplyAction="http://tempuri.org/IAuth/LoginResponse")]
    string Login(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Login", ReplyAction="http://tempuri.org/IAuth/LoginResponse")]
    System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAuthChannel : IAuth, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AuthClient : System.ServiceModel.ClientBase<IAuth>, IAuth
{
    
    public AuthClient()
    {
    }
    
    public AuthClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AuthClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Register(string username, string password)
    {
        return base.Channel.Register(username, password);
    }
    
    public System.Threading.Tasks.Task<string> RegisterAsync(string username, string password)
    {
        return base.Channel.RegisterAsync(username, password);
    }
    
    public string Login(string username, string password)
    {
        return base.Channel.Login(username, password);
    }
    
    public System.Threading.Tasks.Task<string> LoginAsync(string username, string password)
    {
        return base.Channel.LoginAsync(username, password);
    }
}
namespace Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profiles", Namespace="http://schemas.datacontract.org/2004/07/Models")]
    public partial class Profiles : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FirstNameField;
        
        private long IINField;
        
        private System.Guid IdField;
        
        private string PatronymicField;
        
        private string SurnameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IIN
        {
            get
            {
                return this.IINField;
            }
            set
            {
                this.IINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic
        {
            get
            {
                return this.PatronymicField;
            }
            set
            {
                this.PatronymicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
}
